### ISSUE TITLE
Conservation prediction from exisiting embedding

### ISSUE THREAD

**Issue by kaysc** [Rostlab/VESPA#5]
Hi there

I am trying to use the VESPA conservation prediction starting from UniProt-provided ProtT5 embeddings, however, I always get a "TypeError: h5py objects cannot be pickled".

The command I use (boiled down to the simplest form) is just  "vespa_conspred per_residue.h5" where the .h5  is an embedding retrieved from UniProt. Any help or pointers are appreciated.

Error trace:
> [~] vespa_conspred per_residue.h5      
> ######################## Start Conservation Prediction #########################
>  Load model! 
>  Predict Conservation! 
> Traceback (most recent call last):
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/bin/vespa_conspred", line 8, in <module>
>     sys.exit(main())
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/site-packages/vespa/scripts/conspred.py", line 141, in main
>     run_conspred(**arguments)
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/site-packages/vespa/scripts/conspred.py", line 108, in run_conspred
>     predictions = conspred.conservation_prediction(
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/site-packages/vespa/predict/conspred.py", line 143, in conservation_prediction
>     for i, (pdb_ids, X, lens) in enumerate(data_loader):
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
>     return self._get_iterator()
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 381, in _get_iterator
>     return _MultiProcessingDataLoaderIter(self)
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1034, in __init__
>     w.start()
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/multiprocessing/process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
>     return Popen(process_obj)
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
>     super().__init__(process_obj)
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
>     self._launch(process_obj)
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
>     reduction.dump(process_obj, fp)
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
>   File "/Users/nqz918/opt/anaconda3/envs/vespa/lib/python3.9/site-packages/h5py/_hl/base.py", line 368, in __getnewargs__
>     raise TypeError("h5py objects cannot be pickled")
> TypeError: h5py objects cannot be pickled

**Comment by kaysc** [comment]
Changing num_workers in get_dataloader() in predict/conspred.py to num_workers=1 did the trick.
