### ISSUE TITLE
Vespa_run. Error with large datasets - 'NoneType' object has no attribute 'exists'

### ISSUE THREAD

**Issue by hcordoba** [Rostlab/VESPA#8]
Hi!
I hope you are doing great!
@mheinzinger 
I ran VESPA and VESPAI with a few sequences and it ran smoothly. However, I am running VESPAI with my 27k proteins. The steps 1-3 ran with no problem, but once I want to run `vespa_run` I get some `AttributeError: 'NoneType' object has no attribute...` error.
Here is my code and the output:
input: `vespa_run data/protein_primaryTranscriptOnly.fasta --output predictions/ --h5_output data/`
output:
`########################### Start Vespa Predictions ############################
Traceback (most recent call last):
  File "/home/hac89/.conda/envs/tensf113/bin/vespa_run", line 8, in <module>
    sys.exit(main())
  File "/home/hac89/.conda/envs/tensf113/lib/python3.8/site-packages/vespa/scripts/vespa_run.py", line 159, in main
    run_vespa(**arguments)
  File "/home/hac89/.conda/envs/tensf113/lib/python3.8/site-packages/vespa/scripts/vespa_run.py", line 127, in run_vespa
    input["logodds"] = predictor.parse_logodds_input(T5_input)
  File "/home/hac89/.conda/envs/tensf113/lib/python3.8/site-packages/vespa/predict/vespa.py", line 106, in parse_logodds_input
    if not input_file.exists() or not input_file.is_file():
AttributeError: 'NoneType' object has no attribute 'exists'
`
It may be related to #6 

Thank you in advance!

**Comment by hcordoba** [comment]
UPDATE: If running the automatic mode 'Quickstart', I did not have problems. That is a way to go.
